### ISSUE TITLE
Redirect to checkout

### ISSUE THREAD

**Issue by cristianciuberea** [isabelc/WooCommerce-Max-Quantity#12]
Hello,

Can i make that instead of showing an error page to be redirected to cart?

I use a direct checkout plugin, and every time someone click on a buy button they add the product to cart... so i want to limit this and i want to use this plugin.

But if the product is added already, it gives an error message. Can i make that instead of showing the error message to go to cart directly? 

Thanks

**Comment by isabelc** [comment]
Very sorry for the delay. Version 1.3 adds compatibility with the WooCommerce Direct Checkout plugin.
