### ISSUE TITLE
Variable product not working even with backorders disabled

### ISSUE THREAD

**Issue by alai6039** [isabelc/WooCommerce-Max-Quantity#17]
Hi Isabel, 

First off, thank you so much for the plugin.  Literally exactly what I needed! 

I have an issue where my customers are not allowed to purchase a product if it is a variable product.  

Scenario:  If a product has variations,  users can not purchase any of the variable product. Error message will return that the product is out of stock.

**Comment by alai6039** [comment]
I also just saw your other bug: "Limit does not work with Variable products when backorders are allowed. "

I have disabled backorders and it is still acting the same way.

**Comment by isabelc** [comment]
Version 1.4.3 fixes an issue with Variable products.
